// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_weights.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_5fweights_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_5fweights_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_5fweights_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_5fweights_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_5fweights_2eproto;
class SchedulingWeights;
struct SchedulingWeightsDefaultTypeInternal;
extern SchedulingWeightsDefaultTypeInternal _SchedulingWeights_default_instance_;
class UeWeight;
struct UeWeightDefaultTypeInternal;
extern UeWeightDefaultTypeInternal _UeWeight_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SchedulingWeights* Arena::CreateMaybeMessage<::SchedulingWeights>(Arena*);
template<> ::UeWeight* Arena::CreateMaybeMessage<::UeWeight>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum ControlMode : int {
  CONTROL_MODE_WEIGHTS = 0,
  CONTROL_MODE_ELIGIBILITY = 1,
  ControlMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ControlMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ControlMode_IsValid(int value);
constexpr ControlMode ControlMode_MIN = CONTROL_MODE_WEIGHTS;
constexpr ControlMode ControlMode_MAX = CONTROL_MODE_ELIGIBILITY;
constexpr int ControlMode_ARRAYSIZE = ControlMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ControlMode_descriptor();
template<typename T>
inline const std::string& ControlMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ControlMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ControlMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ControlMode_descriptor(), enum_t_value);
}
inline bool ControlMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ControlMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ControlMode>(
    ControlMode_descriptor(), name, value);
}
// ===================================================================

class SchedulingWeights final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SchedulingWeights) */ {
 public:
  inline SchedulingWeights() : SchedulingWeights(nullptr) {}
  ~SchedulingWeights() override;
  explicit PROTOBUF_CONSTEXPR SchedulingWeights(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SchedulingWeights(const SchedulingWeights& from);
  SchedulingWeights(SchedulingWeights&& from) noexcept
    : SchedulingWeights() {
    *this = ::std::move(from);
  }

  inline SchedulingWeights& operator=(const SchedulingWeights& from) {
    CopyFrom(from);
    return *this;
  }
  inline SchedulingWeights& operator=(SchedulingWeights&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SchedulingWeights& default_instance() {
    return *internal_default_instance();
  }
  static inline const SchedulingWeights* internal_default_instance() {
    return reinterpret_cast<const SchedulingWeights*>(
               &_SchedulingWeights_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SchedulingWeights& a, SchedulingWeights& b) {
    a.Swap(&b);
  }
  inline void Swap(SchedulingWeights* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SchedulingWeights* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SchedulingWeights* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SchedulingWeights>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SchedulingWeights& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SchedulingWeights& from) {
    SchedulingWeights::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SchedulingWeights* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SchedulingWeights";
  }
  protected:
  explicit SchedulingWeights(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUeWeightsFieldNumber = 3,
    kDlEligibleRntisFieldNumber = 8,
    kUlEligibleRntisFieldNumber = 9,
    kAlgorithmFieldNumber = 6,
    kRanIndexFieldNumber = 1,
    kTtiIndexFieldNumber = 2,
    kPolicyEpochFieldNumber = 5,
    kDecisionNativeSlotFieldNumber = 7,
    kModeFieldNumber = 4,
  };
  // repeated .UeWeight ue_weights = 3;
  int ue_weights_size() const;
  private:
  int _internal_ue_weights_size() const;
  public:
  void clear_ue_weights();
  ::UeWeight* mutable_ue_weights(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >*
      mutable_ue_weights();
  private:
  const ::UeWeight& _internal_ue_weights(int index) const;
  ::UeWeight* _internal_add_ue_weights();
  public:
  const ::UeWeight& ue_weights(int index) const;
  ::UeWeight* add_ue_weights();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >&
      ue_weights() const;

  // repeated uint32 dl_eligible_rntis = 8;
  int dl_eligible_rntis_size() const;
  private:
  int _internal_dl_eligible_rntis_size() const;
  public:
  void clear_dl_eligible_rntis();
  private:
  uint32_t _internal_dl_eligible_rntis(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_dl_eligible_rntis() const;
  void _internal_add_dl_eligible_rntis(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_dl_eligible_rntis();
  public:
  uint32_t dl_eligible_rntis(int index) const;
  void set_dl_eligible_rntis(int index, uint32_t value);
  void add_dl_eligible_rntis(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      dl_eligible_rntis() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_dl_eligible_rntis();

  // repeated uint32 ul_eligible_rntis = 9;
  int ul_eligible_rntis_size() const;
  private:
  int _internal_ul_eligible_rntis_size() const;
  public:
  void clear_ul_eligible_rntis();
  private:
  uint32_t _internal_ul_eligible_rntis(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_ul_eligible_rntis() const;
  void _internal_add_ul_eligible_rntis(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_ul_eligible_rntis();
  public:
  uint32_t ul_eligible_rntis(int index) const;
  void set_ul_eligible_rntis(int index, uint32_t value);
  void add_ul_eligible_rntis(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      ul_eligible_rntis() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_ul_eligible_rntis();

  // string algorithm = 6;
  void clear_algorithm();
  const std::string& algorithm() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_algorithm(ArgT0&& arg0, ArgT... args);
  std::string* mutable_algorithm();
  PROTOBUF_NODISCARD std::string* release_algorithm();
  void set_allocated_algorithm(std::string* algorithm);
  private:
  const std::string& _internal_algorithm() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_algorithm(const std::string& value);
  std::string* _internal_mutable_algorithm();
  public:

  // uint32 ran_index = 1;
  void clear_ran_index();
  uint32_t ran_index() const;
  void set_ran_index(uint32_t value);
  private:
  uint32_t _internal_ran_index() const;
  void _internal_set_ran_index(uint32_t value);
  public:

  // uint32 tti_index = 2;
  void clear_tti_index();
  uint32_t tti_index() const;
  void set_tti_index(uint32_t value);
  private:
  uint32_t _internal_tti_index() const;
  void _internal_set_tti_index(uint32_t value);
  public:

  // uint64 policy_epoch = 5;
  void clear_policy_epoch();
  uint64_t policy_epoch() const;
  void set_policy_epoch(uint64_t value);
  private:
  uint64_t _internal_policy_epoch() const;
  void _internal_set_policy_epoch(uint64_t value);
  public:

  // uint64 decision_native_slot = 7;
  void clear_decision_native_slot();
  uint64_t decision_native_slot() const;
  void set_decision_native_slot(uint64_t value);
  private:
  uint64_t _internal_decision_native_slot() const;
  void _internal_set_decision_native_slot(uint64_t value);
  public:

  // .ControlMode mode = 4;
  void clear_mode();
  ::ControlMode mode() const;
  void set_mode(::ControlMode value);
  private:
  ::ControlMode _internal_mode() const;
  void _internal_set_mode(::ControlMode value);
  public:

  // @@protoc_insertion_point(class_scope:SchedulingWeights)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight > ue_weights_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > dl_eligible_rntis_;
    mutable std::atomic<int> _dl_eligible_rntis_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > ul_eligible_rntis_;
    mutable std::atomic<int> _ul_eligible_rntis_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr algorithm_;
    uint32_t ran_index_;
    uint32_t tti_index_;
    uint64_t policy_epoch_;
    uint64_t decision_native_slot_;
    int mode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fweights_2eproto;
};
// -------------------------------------------------------------------

class UeWeight final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UeWeight) */ {
 public:
  inline UeWeight() : UeWeight(nullptr) {}
  ~UeWeight() override;
  explicit PROTOBUF_CONSTEXPR UeWeight(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UeWeight(const UeWeight& from);
  UeWeight(UeWeight&& from) noexcept
    : UeWeight() {
    *this = ::std::move(from);
  }

  inline UeWeight& operator=(const UeWeight& from) {
    CopyFrom(from);
    return *this;
  }
  inline UeWeight& operator=(UeWeight&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UeWeight& default_instance() {
    return *internal_default_instance();
  }
  static inline const UeWeight* internal_default_instance() {
    return reinterpret_cast<const UeWeight*>(
               &_UeWeight_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UeWeight& a, UeWeight& b) {
    a.Swap(&b);
  }
  inline void Swap(UeWeight* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UeWeight* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UeWeight* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UeWeight>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UeWeight& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UeWeight& from) {
    UeWeight::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UeWeight* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UeWeight";
  }
  protected:
  explicit UeWeight(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRntiFieldNumber = 1,
    kWeightFieldNumber = 2,
  };
  // uint32 rnti = 1;
  void clear_rnti();
  uint32_t rnti() const;
  void set_rnti(uint32_t value);
  private:
  uint32_t _internal_rnti() const;
  void _internal_set_rnti(uint32_t value);
  public:

  // float weight = 2;
  void clear_weight();
  float weight() const;
  void set_weight(float value);
  private:
  float _internal_weight() const;
  void _internal_set_weight(float value);
  public:

  // @@protoc_insertion_point(class_scope:UeWeight)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t rnti_;
    float weight_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_5fweights_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SchedulingWeights

// uint32 ran_index = 1;
inline void SchedulingWeights::clear_ran_index() {
  _impl_.ran_index_ = 0u;
}
inline uint32_t SchedulingWeights::_internal_ran_index() const {
  return _impl_.ran_index_;
}
inline uint32_t SchedulingWeights::ran_index() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.ran_index)
  return _internal_ran_index();
}
inline void SchedulingWeights::_internal_set_ran_index(uint32_t value) {

  _impl_.ran_index_ = value;
}
inline void SchedulingWeights::set_ran_index(uint32_t value) {
  _internal_set_ran_index(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.ran_index)
}

// uint32 tti_index = 2;
inline void SchedulingWeights::clear_tti_index() {
  _impl_.tti_index_ = 0u;
}
inline uint32_t SchedulingWeights::_internal_tti_index() const {
  return _impl_.tti_index_;
}
inline uint32_t SchedulingWeights::tti_index() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.tti_index)
  return _internal_tti_index();
}
inline void SchedulingWeights::_internal_set_tti_index(uint32_t value) {

  _impl_.tti_index_ = value;
}
inline void SchedulingWeights::set_tti_index(uint32_t value) {
  _internal_set_tti_index(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.tti_index)
}

// repeated .UeWeight ue_weights = 3;
inline int SchedulingWeights::_internal_ue_weights_size() const {
  return _impl_.ue_weights_.size();
}
inline int SchedulingWeights::ue_weights_size() const {
  return _internal_ue_weights_size();
}
inline void SchedulingWeights::clear_ue_weights() {
  _impl_.ue_weights_.Clear();
}
inline ::UeWeight* SchedulingWeights::mutable_ue_weights(int index) {
  // @@protoc_insertion_point(field_mutable:SchedulingWeights.ue_weights)
  return _impl_.ue_weights_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >*
SchedulingWeights::mutable_ue_weights() {
  // @@protoc_insertion_point(field_mutable_list:SchedulingWeights.ue_weights)
  return &_impl_.ue_weights_;
}
inline const ::UeWeight& SchedulingWeights::_internal_ue_weights(int index) const {
  return _impl_.ue_weights_.Get(index);
}
inline const ::UeWeight& SchedulingWeights::ue_weights(int index) const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.ue_weights)
  return _internal_ue_weights(index);
}
inline ::UeWeight* SchedulingWeights::_internal_add_ue_weights() {
  return _impl_.ue_weights_.Add();
}
inline ::UeWeight* SchedulingWeights::add_ue_weights() {
  ::UeWeight* _add = _internal_add_ue_weights();
  // @@protoc_insertion_point(field_add:SchedulingWeights.ue_weights)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::UeWeight >&
SchedulingWeights::ue_weights() const {
  // @@protoc_insertion_point(field_list:SchedulingWeights.ue_weights)
  return _impl_.ue_weights_;
}

// .ControlMode mode = 4;
inline void SchedulingWeights::clear_mode() {
  _impl_.mode_ = 0;
}
inline ::ControlMode SchedulingWeights::_internal_mode() const {
  return static_cast< ::ControlMode >(_impl_.mode_);
}
inline ::ControlMode SchedulingWeights::mode() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.mode)
  return _internal_mode();
}
inline void SchedulingWeights::_internal_set_mode(::ControlMode value) {

  _impl_.mode_ = value;
}
inline void SchedulingWeights::set_mode(::ControlMode value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.mode)
}

// uint64 policy_epoch = 5;
inline void SchedulingWeights::clear_policy_epoch() {
  _impl_.policy_epoch_ = uint64_t{0u};
}
inline uint64_t SchedulingWeights::_internal_policy_epoch() const {
  return _impl_.policy_epoch_;
}
inline uint64_t SchedulingWeights::policy_epoch() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.policy_epoch)
  return _internal_policy_epoch();
}
inline void SchedulingWeights::_internal_set_policy_epoch(uint64_t value) {

  _impl_.policy_epoch_ = value;
}
inline void SchedulingWeights::set_policy_epoch(uint64_t value) {
  _internal_set_policy_epoch(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.policy_epoch)
}

// string algorithm = 6;
inline void SchedulingWeights::clear_algorithm() {
  _impl_.algorithm_.ClearToEmpty();
}
inline const std::string& SchedulingWeights::algorithm() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.algorithm)
  return _internal_algorithm();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SchedulingWeights::set_algorithm(ArgT0&& arg0, ArgT... args) {

 _impl_.algorithm_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SchedulingWeights.algorithm)
}
inline std::string* SchedulingWeights::mutable_algorithm() {
  std::string* _s = _internal_mutable_algorithm();
  // @@protoc_insertion_point(field_mutable:SchedulingWeights.algorithm)
  return _s;
}
inline const std::string& SchedulingWeights::_internal_algorithm() const {
  return _impl_.algorithm_.Get();
}
inline void SchedulingWeights::_internal_set_algorithm(const std::string& value) {

  _impl_.algorithm_.Set(value, GetArenaForAllocation());
}
inline std::string* SchedulingWeights::_internal_mutable_algorithm() {

  return _impl_.algorithm_.Mutable(GetArenaForAllocation());
}
inline std::string* SchedulingWeights::release_algorithm() {
  // @@protoc_insertion_point(field_release:SchedulingWeights.algorithm)
  return _impl_.algorithm_.Release();
}
inline void SchedulingWeights::set_allocated_algorithm(std::string* algorithm) {
  if (algorithm != nullptr) {

  } else {

  }
  _impl_.algorithm_.SetAllocated(algorithm, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.algorithm_.IsDefault()) {
    _impl_.algorithm_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SchedulingWeights.algorithm)
}

// uint64 decision_native_slot = 7;
inline void SchedulingWeights::clear_decision_native_slot() {
  _impl_.decision_native_slot_ = uint64_t{0u};
}
inline uint64_t SchedulingWeights::_internal_decision_native_slot() const {
  return _impl_.decision_native_slot_;
}
inline uint64_t SchedulingWeights::decision_native_slot() const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.decision_native_slot)
  return _internal_decision_native_slot();
}
inline void SchedulingWeights::_internal_set_decision_native_slot(uint64_t value) {

  _impl_.decision_native_slot_ = value;
}
inline void SchedulingWeights::set_decision_native_slot(uint64_t value) {
  _internal_set_decision_native_slot(value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.decision_native_slot)
}

// repeated uint32 dl_eligible_rntis = 8;
inline int SchedulingWeights::_internal_dl_eligible_rntis_size() const {
  return _impl_.dl_eligible_rntis_.size();
}
inline int SchedulingWeights::dl_eligible_rntis_size() const {
  return _internal_dl_eligible_rntis_size();
}
inline void SchedulingWeights::clear_dl_eligible_rntis() {
  _impl_.dl_eligible_rntis_.Clear();
}
inline uint32_t SchedulingWeights::_internal_dl_eligible_rntis(int index) const {
  return _impl_.dl_eligible_rntis_.Get(index);
}
inline uint32_t SchedulingWeights::dl_eligible_rntis(int index) const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.dl_eligible_rntis)
  return _internal_dl_eligible_rntis(index);
}
inline void SchedulingWeights::set_dl_eligible_rntis(int index, uint32_t value) {
  _impl_.dl_eligible_rntis_.Set(index, value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.dl_eligible_rntis)
}
inline void SchedulingWeights::_internal_add_dl_eligible_rntis(uint32_t value) {
  _impl_.dl_eligible_rntis_.Add(value);
}
inline void SchedulingWeights::add_dl_eligible_rntis(uint32_t value) {
  _internal_add_dl_eligible_rntis(value);
  // @@protoc_insertion_point(field_add:SchedulingWeights.dl_eligible_rntis)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
SchedulingWeights::_internal_dl_eligible_rntis() const {
  return _impl_.dl_eligible_rntis_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
SchedulingWeights::dl_eligible_rntis() const {
  // @@protoc_insertion_point(field_list:SchedulingWeights.dl_eligible_rntis)
  return _internal_dl_eligible_rntis();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
SchedulingWeights::_internal_mutable_dl_eligible_rntis() {
  return &_impl_.dl_eligible_rntis_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
SchedulingWeights::mutable_dl_eligible_rntis() {
  // @@protoc_insertion_point(field_mutable_list:SchedulingWeights.dl_eligible_rntis)
  return _internal_mutable_dl_eligible_rntis();
}

// repeated uint32 ul_eligible_rntis = 9;
inline int SchedulingWeights::_internal_ul_eligible_rntis_size() const {
  return _impl_.ul_eligible_rntis_.size();
}
inline int SchedulingWeights::ul_eligible_rntis_size() const {
  return _internal_ul_eligible_rntis_size();
}
inline void SchedulingWeights::clear_ul_eligible_rntis() {
  _impl_.ul_eligible_rntis_.Clear();
}
inline uint32_t SchedulingWeights::_internal_ul_eligible_rntis(int index) const {
  return _impl_.ul_eligible_rntis_.Get(index);
}
inline uint32_t SchedulingWeights::ul_eligible_rntis(int index) const {
  // @@protoc_insertion_point(field_get:SchedulingWeights.ul_eligible_rntis)
  return _internal_ul_eligible_rntis(index);
}
inline void SchedulingWeights::set_ul_eligible_rntis(int index, uint32_t value) {
  _impl_.ul_eligible_rntis_.Set(index, value);
  // @@protoc_insertion_point(field_set:SchedulingWeights.ul_eligible_rntis)
}
inline void SchedulingWeights::_internal_add_ul_eligible_rntis(uint32_t value) {
  _impl_.ul_eligible_rntis_.Add(value);
}
inline void SchedulingWeights::add_ul_eligible_rntis(uint32_t value) {
  _internal_add_ul_eligible_rntis(value);
  // @@protoc_insertion_point(field_add:SchedulingWeights.ul_eligible_rntis)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
SchedulingWeights::_internal_ul_eligible_rntis() const {
  return _impl_.ul_eligible_rntis_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
SchedulingWeights::ul_eligible_rntis() const {
  // @@protoc_insertion_point(field_list:SchedulingWeights.ul_eligible_rntis)
  return _internal_ul_eligible_rntis();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
SchedulingWeights::_internal_mutable_ul_eligible_rntis() {
  return &_impl_.ul_eligible_rntis_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
SchedulingWeights::mutable_ul_eligible_rntis() {
  // @@protoc_insertion_point(field_mutable_list:SchedulingWeights.ul_eligible_rntis)
  return _internal_mutable_ul_eligible_rntis();
}

// -------------------------------------------------------------------

// UeWeight

// uint32 rnti = 1;
inline void UeWeight::clear_rnti() {
  _impl_.rnti_ = 0u;
}
inline uint32_t UeWeight::_internal_rnti() const {
  return _impl_.rnti_;
}
inline uint32_t UeWeight::rnti() const {
  // @@protoc_insertion_point(field_get:UeWeight.rnti)
  return _internal_rnti();
}
inline void UeWeight::_internal_set_rnti(uint32_t value) {

  _impl_.rnti_ = value;
}
inline void UeWeight::set_rnti(uint32_t value) {
  _internal_set_rnti(value);
  // @@protoc_insertion_point(field_set:UeWeight.rnti)
}

// float weight = 2;
inline void UeWeight::clear_weight() {
  _impl_.weight_ = 0;
}
inline float UeWeight::_internal_weight() const {
  return _impl_.weight_;
}
inline float UeWeight::weight() const {
  // @@protoc_insertion_point(field_get:UeWeight.weight)
  return _internal_weight();
}
inline void UeWeight::_internal_set_weight(float value) {

  _impl_.weight_ = value;
}
inline void UeWeight::set_weight(float value) {
  _internal_set_weight(value);
  // @@protoc_insertion_point(field_set:UeWeight.weight)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ControlMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ControlMode>() {
  return ::ControlMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_5fweights_2eproto
